### ISSUE TITLE
Native auth

### ISSUE THREAD

**Issue by bonny1992** [relvacode/storm#10]
I'll be honest, this seems to be currently the best way to manage Deluge from a iOS device.

Sadly, when using the app with Nginx basic auth on said iOS device will ask everytime for the password, and we can't do the `user:pass@url.com` trick to bypass it. Plus, if you use the PWA (shortcut from home screen), it won't be autocompleted like it was in Safari.

So, I think we'd need a native auth mechanism, at least we can save the password inside the apple keychain, or another password manager.

Probably with this, plus #9 , Storm would be a extremely valid substitute as the original web ui (but actually usable on mobile).

**Comment by bonny1992** [comment]
That was very fast, thank you @relvacode !

Is there any ETA for an updated image on docker hub? In the meanwhile I'm gonna build it myself :)

**Comment by relvacode** [comment]
I'm working on a new method for building releases, I'll let you know when that's ready. #15

**Comment by bonny1992** [comment]
Oh perfect @relvacode because I'm failing dramatically to build the image myself lol

Thank you in the meanwhile!

**Comment by relvacode** [comment]
@bonny1992 the new build pipeline is in place. Latest images are now available.

Note I've moved the repository to GitHub's Container Registry https://github.com/relvacode/storm/pkgs/container/storm

**Comment by bonny1992** [comment]
Many thanks @relvacode !
That was very fast! :D
