### ISSUE TITLE
Install without Docker 

### ISSUE THREAD

**Issue by antoine2tt** [relvacode/storm#26]
Hello ! 

Your project seems very cool !! 

Is there a way to install it without using Docker ? 

Thank you!

**Comment by relvacode** [comment]
There are binary distributions available for most platforms under the releases page https://github.com/relvacode/storm/releases/tag/v1.0.2

**Comment by antoine2tt** [comment]
My bad ! 

I didn’t search enough, I’ll check that tomorrow. 

Thank you ! Have a great day

**Comment by relvacode** [comment]
No problem, I'll make a note to include that in the README
