### ISSUE TITLE
Buttons too small for text in "Add Torrent" windows

### ISSUE THREAD

**Issue by cmbarba** [relvacode/storm#31]
![Screenshot 2022-01-06 031857](https://user-images.githubusercontent.com/82081846/148351893-5c554e4a-f76f-41e7-898a-2f467b8075c0.png)
![Screenshot 2022-01-06 032000](https://user-images.githubusercontent.com/82081846/148351895-ca311038-9cc1-4809-8774-01473e034871.png)
![Screenshot 2022-01-06 032018](https://user-images.githubusercontent.com/82081846/148351896-c7de1c60-e89c-4d38-b1da-ddf627c40b06.png)

**Comment by cmbarba** [comment]
Thank you for your work! This is just something small I noticed. It looks similar on mobile.

**Comment by relvacode** [comment]
Which browser are you using?

**Comment by cmbarba** [comment]
On desktop I'm using Firefox 95.0.2. On mobile I'm using Firefox Nightly 97.0a1.
