### ISSUE TITLE
More filtering needed

### ISSUE THREAD

**Issue by bonny1992** [relvacode/storm#35]
I suggest adding more filtering, to further mirror Deluge original filtering.

For example, (currently) active torrents, or filter by labels.

**Comment by relvacode** [comment]
You can filter by labels using the search bar, but perhaps a dropdown selector would be useful too.

A meta state to include all active statuses also sounds useful

**Comment by jorritsmit** [comment]
it would also be useful to reverse sort, for example for getting the latest added torrents on top
