### ISSUE TITLE
Show torrents created outside of Storm (with Deluge 2)

### ISSUE THREAD

**Issue by deardaniel** [relvacode/storm#38]
I was using Storm with Deluge 1.4.3 (`linuxserver/deluge:143-data-2`) without issue. After upgrading to Deluge 2.0.5 (`linuxserver/deluge` at time of writing), Storm showed "No torrents". When I uploaded a new torrent from Storm, it appeared. When I uploaded a new torrent from Deluge's WebUI, it did not.

I noticed in Deluge that the Storm-uploaded torrent had an "owner" of `storm` but others were `localclient`. Is this a limitation of Deluge's v2 API? If so, should it be documented?

Or can Storm change how it create Deluge RPCs to retrieve all torrents?

**Comment by relvacode** [comment]
Interesting. Do you see the same behaviour in reverse (does the Deluge WebUI see torrents created by Storm)? Are you using different RPC accounts for both?

**Comment by deardaniel** [comment]
Aha, maybe this was an error in my decision to make a separate Deluge user with Storm.

Looking at https://github.com/relvacode/storm/blob/master/docker-compose/auth and mirroring that single-user `localclient` setup locally seems to solve the problem. I had made a separate `storm` user but with Deluge 2, it seems like I should have Storm use the `localclient` user if I want to share data.

**Comment by relvacode** [comment]
Okay thanks for the discovery. I've made a note about it in the README. If this becomes particularly problematic in future we can investigate if it's possible to see system-wide torrents. I don't think many people will be presenting the RPC directly and instead will be mostly using client-side auth anyway.
