### ISSUE TITLE
problem connecting to deluge

### ISSUE THREAD

**Issue by Darkmagister** [relvacode/storm#43]
hello, i have a deluce container with open port 55847 for rpc (58846 on container and 58847 on host) i created a container for storm (i haven't used a separate network for this two both are in bridge network) i added the host ip machine as host and the custom port, but i get this error while connecting:
`ERROR	api	storm/api.go:206	Internal Server Error	{"Method": "GET", "URL": "/api/plugins", "RemoteAddr": "172.17.0.1:37790", "Time": "2023-01-15T23:29:20.237Z", "StatusCode": 500, "ResponseSize": 34, "Duration": "6.424707983s", "error": "context canceled"}`

i don't understand why that ip and that port ... and what context canceled mean... 

also to be sure i tried with the official deluge thin client to connect to that port and with the user and password and that work great

any idea? 

thanks

**Comment by relvacode** [comment]
You can ignore RemoteAddr, that's the client address of the HTTP request.

Have you check that you have `DELUGE_RPC_VERSION` set to `v2` if you're using Deluge v2?

**Comment by Darkmagister** [comment]
yes thanks that works adding the v2 param and now storm works, i was expeting storm to have more info (tracker, list file, peer and other options) but now i can test it

**Comment by relvacode** [comment]
Feel free to open a PR with new features
