### ISSUE TITLE
Question (newbie) -- how to have storm up an running

### ISSUE THREAD

**Issue by valsamis-d** [relvacode/storm#55]
Hello guys,

I followed all instructions:

1) installed Docker in my OSMC RPi2
2) installed Sorm

All successful! Btw amazing interface 😄 Thanks!

How do I autostart Storm after a reboot and have it running in the background?

**Comment by relvacode** [comment]
In your `docker run` command you need to add the options `-d` (detach, run in background) and `--restart=unless-stopped` to have docker start the container when it starts

**Comment by valsamis-d** [comment]
@relvacode thanks for the response!

I tried the following:

```
docker run \
  --network host \
  --restart=unless-stopped \
  -d \
  -p 8221:8221 \
  -e DELUGE_RPC_HOSTNAME=localhost \
  -e DELUGE_RPC_USERNAME=user \
  -e DELUGE_RPC_PASSWORD=pass \
  -e DELUGE_RPC_VERSION=v2 \
  ghcr.io/relvacode/storm
```

All was good until I reboot my RPi2. I just couldn't open the WebUI. Checked with "_docker top storm_" and found out that the container was not running. Then I removed the "_-d_":

```
docker run \
  --network host \
  --restart=unless-stopped \
  -p 8221:8221 \
  -e DELUGE_RPC_HOSTNAME=localhost \
  -e DELUGE_RPC_USERNAME=user \
  -e DELUGE_RPC_PASSWORD=pass \
  -e DELUGE_RPC_VERSION=v2 \
  ghcr.io/relvacode/storm
```

and got the following error:

`listen tcp :8221: bind: address already in use`

To check who's using the port, I did "_ss -tanp | grep 8221_" :

`LISTEN    0      4096               *:8221              *:*`

Now, I cannot start Storm again.

Any pointers?

**Comment by valsamis-d** [comment]
Hello again,

I think I found my issue here.

The behavior was actually due to two reasons:

1) My deluged deamon was failing to start after reboot, due to dependencies. I fixed that.

2) several Storm dockers were found running. I stopped all of them, removed them.

After that I restarted Storm docker using -d and --restart, reboot and now all is good! 

I'm closing this.
