### ISSUE TITLE
Running on armhf architecture

### ISSUE THREAD

**Issue by jacknbeans** [relvacode/storm#7]
I tried booting up the docker image on my raspberry pi 4, but ran into issues where the container just exits with this error message:

```
standard_init_linux.go:219: exec user process caused: exec format error
```

I know next to nothing about container development or go, so hoping that you might be able to shed some light on this?

**Comment by relvacode** [comment]
Previously I hadn't made multiarch builds for Storm on DockerHub. I've now built images for `amd64` `arm64` and `arm/v7` so you should be able to pull the latest image and get the right one for your architecture. I don't personally have a RaspberryPi to test with but this should work?

**Comment by jacknbeans** [comment]
Sorry it took me so long, I've been busy. But I found some time to get around to testing this out and it works! So thanks for releasing the arm versions 🙏
