### ISSUE TITLE
Binary Releases

### ISSUE THREAD

**Issue by sulliops** [relvacode/storm#8]
Hi all,

I know that Storm is meant to be run with Docker, but I'm really trying to avoid it if possible. My seedbox lacks VT-X support, so I was originally under the impression that I wouldn't be able to use Docker, and thus I setup Deluge independently. Then, I found out Docker will run without VT-X on 64-bit Linux distros running newer kernel versions, and now I'm struggling to get Storm running. 

I'm running the following command to start the Storm image:

```
docker run -p 8221:8221 -e DELUGE_RPC_HOSTNAME="[PUBLIC_IP]" -e DELUGE_RPC_USERNAME="storm" -e DELUGE_RPC_PASSWORD="storm" -e DELUGE_RPC_VERSION=v2 relvacode/storm
```

My Deluge setup is pretty standard, and I know the ports are forwarded because I can access Deluge's normal WebUI just fine. I've got a user setup for Storm under my Deluge auth config, so login shouldn't be an issue, and RPC is definitely enabled. The connection to the Deluge daemon is being made, but I receive the following error:

```
ERROR	api	storm/api.go:76		{"Method": "GET", "URL": "/api/torrents", "RemoteAddr": "172.18.0.1:46680", "Time": "2021-10-05T01:21:04.166Z", "StatusCode": 0, "ResponseSize": 0, "Duration": "-2562047h47m16.854775808s", "error": "context canceled"}
```

Not sure where that RemoteAddr is coming from, since none of my network adapters use 172.18.x.x for anything.

Any ideas?

**Comment by relvacode** [comment]
Is Deluge also running inside a container? If so you should use the `DELUGE_RPC_HOSTNAME` of the deluge container name.

If not, you could try running the container with `--net=host`, this will bypass container network isolation and configure the container's networking as if it were a regular binary on your host. This way you can use `DELUGE_RPC_HOSTNAME=localhost`.

Failing that I'm working on a build pipeline to publish binaries to the git release. 

I would still recommend Docker though. There's a learning curve but once you get the hang of it, it really does make deployment and management a bunch easier. (See my other project https://github.com/relvacode/mediastack, which enables stuff like torrent traffic over VPN and Google authentication for web apps, etc)

**Comment by sulliops** [comment]
Running the Storm container with `--net=host` results in Storm not being published on port 8221, not even for localhost. 

I'll definitely be interested in a binary release when it's available.

**Comment by relvacode** [comment]
I'm working on binary releases now, but I think I've come across your issue myself.

You may have luck with `--deluge-version=v2` / `DELUGE_RPC_VERSION=v2` as Deluge v2 seems to stall on connections made by a v1 client

**Comment by relvacode** [comment]
@sulliops Binaries for all platforms can now be downloaded from the GitHub releases page https://github.com/relvacode/storm/releases/tag/v1.0.2
