### ISSUE TITLE
Change torrent labels

### ISSUE THREAD

**Issue by Namaneo** [relvacode/storm#9]
Hi,

First of all, great project! I was looking for a mobile-friendly UI for Deluge, and Storm seems very well suited for that purpose. 🙂 

Unless I missed it, label modification is currently not supported, and this would be a key feature for my usage (my Deluge being part of the Sonarr/Radarr stack). I would be glad to help develop that, but I preferred to have your thoughts first regarding the user experience (e.g. where to put the button, where to display the current label, etc.). 

Would you be interested?

**Comment by bonny1992** [comment]
+1 for this.
I use labels for almost any operation in Deluge (auto move, delete, etc) so for me it's 100%.

As for "graphic" I made this quick example to visualize it:
![image](https://user-images.githubusercontent.com/1154368/146658805-8768f641-4436-4d5b-9275-0c84fa6de222.png)

**Comment by relvacode** [comment]
Implementation requires https://github.com/gdm85/go-libdeluge/pull/40
